name: Build Crispino POS Executables

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build executables
      run: |
        # Build console version
        pyinstaller "Crispino POS (console).spec" --clean --noconfirm
        
        # Build windowed version
        pyinstaller "Crispino POS.spec" --clean --noconfirm
        
    - name: Check built files
      run: |
        ls -la dist/
        
    - name: Test console executable
      timeout-minutes: 2
      run: |
        # Start the exe in background and test if it responds
        Start-Process -FilePath ".\dist\Crispino POS (console).exe" -NoNewWindow
        Start-Sleep -Seconds 10
        
        # Try to connect to the server
        try {
          $response = Invoke-WebRequest -Uri "http://127.0.0.1:8000/" -TimeoutSec 5
          Write-Host "✓ Server responded with status: $($response.StatusCode)"
        } catch {
          Write-Host "⚠ Server test failed (this may be expected in CI): $_"
        }
        
        # Stop any remaining processes
        Get-Process | Where-Object {$_.ProcessName -like "*Crispino*"} | Stop-Process -Force -ErrorAction SilentlyContinue
        
    - name: Package artifacts
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
      run: |
        # Create release directory
        mkdir release
        
        # Copy executables
        Copy-Item "dist\Crispino POS.exe" "release\"
        Copy-Item "dist\Crispino POS (console).exe" "release\"
        
        # Copy documentation and sample data
        Copy-Item "README.md" "release\"
        Copy-Item "assets\*" "release\" -Recurse -ErrorAction SilentlyContinue
        
        # Create ZIP for release
        Compress-Archive -Path "release\*" -DestinationPath "Crispino-POS-Windows.zip"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: crispino-pos-windows
        path: |
          dist/*.exe
          Crispino-POS-Windows.zip
        retention-days: 30
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: Crispino-POS-Windows.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}